# Generated by Django 5.1 on 2024-09-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NginxLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('remote_ip', models.GenericIPAddressField()),
                ('remote_user', models.CharField(max_length=50)),
                ('request', models.CharField(max_length=50)),
                ('response', models.IntegerField()),
                ('bytes', models.IntegerField()),
                ('referrer', models.CharField(max_length=2048)),
                ('agent', models.CharField(max_length=2048)),
            ],
        ),
    ]
